name: hireme_apps
description: "HireMe Apps - Proyek Flutter untuk Aplikasi Pencarian Kerja"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  country_pickers: ^3.0.1
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  dotted_border: ^2.1.0
  google_maps_flutter: ^2.9.0
  sms_autofill: ^2.4.0
  pin_code_fields: ^8.0.1
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  sqflite: ^2.0.3+1
  connectivity_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Sesuaikan dengan aset yang tersedia di proyek Anda.
  assets:
    # - assets/images/  # Pastikan folder ini ada, atau sesuaikan namanya jika perlu

  # Pastikan font ini benar-benar ada di jalur yang didefinisikan.
  fonts:
    - family: DM Sans
      fonts:
        # - asset: assets/fonts/DMSans-Regular.ttf  # Pastikan file ini ada, atau hapus jika tidak diperlukan
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-Italic.ttf
          style: italic
